name: Concurrency-PR
on:  
  push: 
    branches: [ main]  
    
concurrency:
  group: test-on-pr-${{github.head_ref}}
  #group: build-and-test  
  cancel-in-progress: false
  
jobs:  

  build-and-test-on-pr:
    name: build and test on pull request
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
    
      - name: output HeadRef
        run: echo "${{github.head_ref}}"
      
      - name: Get uuid
        id: uuid
        run: |
            uuid=$(uuidgen) >> $GITHUB_ENV
            echo $uuid
            echo "uuidenv=$(echo $uuid)" >> $GITHUB_ENV
            
      - name: write the uuid in the counter-file
        run: |
          echo $uuidenv
          touch counter-file.txt 
          ls
          echo "$uuidenv" > ./counter-file.txt
          cat counter-file.txt
          ls ${{ github.workspace }} #response >> counter-file.txt
          ls ${GITHUB_WORKSPACE}
          chmod u+x "${GITHUB_WORKSPACE}/counter-file.txt"
          ls -lah 

            
      - name: Build The Code
        run: | 
          echo "starting building the code"
          sleep 1m
          echo "Finish the code"
          
          
      - name: Test the code
        run: | 
          echo "starting building the code"
          sleep 1m
          echo "Finish the code"
